name: Validate Delivery

on:
  push:
    branches: [main]
  pull_request:
  pull_request_target:

jobs:
  validate:
    name: Validate Delivery PR
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      # ----------------------------
      # Validate branch name
      # ----------------------------
      - name: Validate branch name
        run: |
          branch="${{ github.head_ref }}"
          echo "Branch: $branch"

          if [[ "$branch" != "" && ! "$branch" =~ ^student-[0-9]+-delivery[1-5]$ ]]; then
            echo "Invalid branch name"
            exit 1
          fi

      # ----------------------------
      # Validate changed files
      # ----------------------------
      - name: Validate changed files
        run: |
          git fetch origin main || true
          files=$(git diff --name-only origin/main...HEAD)

          echo "Changed files:"
          echo "$files"

          count=$(echo "$files" | wc -l)

          if [ "$count" -gt 1 ]; then
            echo "Only ONE file allowed"
            exit 1
          fi

          file=$(echo "$files")

          if [[ "$file" != students/* ]]; then
            echo "File must be inside students/"
            exit 1
          fi

          if [[ "$file" != *delivery1.md && "$file" != *delivery2.md && "$file" != *delivery3.md && "$file" != *delivery4.md && "$file" != *delivery5.md ]]; then
            echo "Invalid file name"
            exit 1
          fi

      # ----------------------------
      # Validate content
      # ----------------------------
      - name: Validate content
        run: |
          file=$(git diff --name-only origin/main...HEAD)

          if [ ! -s "$file" ]; then
            echo "Empty file"
            exit 1
          fi

          echo "Validation passed"
